name: Pre-release Docker Images

on:
  push:
    tags:
      - "v*.*.*-pre-release"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: |
          # Extract version from tag (e.g., v1.2.3-pre-release -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION%-pre-release}
          # Get short SHA
          SHA=$(git rev-parse --short HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "SHA=${SHA}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: dagandersen/argocd-diff-preview:${{ env.VERSION }}-${{ env.SHA }}-${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: |
          # Extract version from tag (e.g., v1.2.3-pre-release -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION%-pre-release}
          # Get short SHA
          SHA=$(git rev-parse --short HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "SHA=${SHA}" >> $GITHUB_ENV
      - name: create manifest
        run: |
          docker buildx imagetools create -t \
            dagandersen/argocd-diff-preview:${{ env.VERSION }}-${{ env.SHA }} \
            dagandersen/argocd-diff-preview:${{ env.VERSION }}-${{ env.SHA }}-amd64 \
            dagandersen/argocd-diff-preview:${{ env.VERSION }}-${{ env.SHA }}-arm64 